name: Shion CI
on:
  push:
    branches:
      - 'dev'
      - 'main'
      - 'ci'
    paths:
      - '**Dockerfile'
      - '**.cxx'
      - '**.ixx'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.cmake'
      - '.github/workflows/ci.yml'
      - '.github/workflows/linux_ci.yml'
      - '.github/workflows/windows_ci.yml'
      - '**CMakeLists.txt'
      - 'dep/**'
  pull_request:
    paths:
      - '**Dockerfile'
      - '**.cxx'
      - '**.ixx'
      - '**.cpp'
      - '**.h'
      - '**.hpp'
      - '**.cmake'
      - '.github/workflows/ci.yml'
      - '.github/workflows/linux_ci.yml'
      - '.github/workflows/windows_ci.yml'
      - '**CMakeLists.txt'
      - 'dep/**'

jobs:
  linux-ci:
    secrets: inherit
    concurrency:
      group: dev-${{ github.workflow }}-${{ github.ref }}-${{ matrix.os.codename }}-${{ matrix.os.arch }}-(${{ matrix.compiler.cxx }}-${{ matrix.compiler.version }}-${{ matrix.build }})
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64 ]
        boost: [ 1.87.0 ]
        os:
          - { name: 'Ubuntu', dist: 'ubuntu', version: 24.04 }
        compiler:
          - { cxx: g++, cc: gcc, version: 14, cmake-flags: '' }
          - { cxx: clang++, cc: clang, version: 19, cmake-flags: '-DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-lc++abi"' }
        build: [ Debug ]
    name: '${{ matrix.os.name }} ${{ matrix.os.version }} ${{ matrix.arch }}'
    uses: ./.github/workflows/linux_ci.yml
    with:
      arch: ${{ matrix.arch }}
      boost: ${{ matrix.boost }}
      os: ${{ matrix.os.dist }}-${{ matrix.os.version }}
      cxx: ${{ matrix.compiler.cxx }}
      cc: ${{ matrix.compiler.cc }}
      cxx-ver: ${{ matrix.compiler.version }}
      cmake-flags: ${{ matrix.compiler.cmake-flags }}
      build: ${{ matrix.build }}

  windows-ci:
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os.dist }}-${{ matrix.os.arch }}-(${{ matrix.compiler.version }}-${{ matrix.build }})
      cancel-in-progress: true
    strategy:
      fail-fast: false # Don't cancel other matrix jobs if one fails
      matrix:
        arch: [ x64 ]
        os:
          - { name: 'Windows', dist: windows, version: 2022 }
        compiler:
          - { version: 2022, generator: "Ninja", concurrency: 4 }
        build: [ Debug ]
    name: '${{ matrix.os.name }} ${{ matrix.arch }}'
    uses: ./.github/workflows/windows_ci.yml
    with:
      arch: ${{ matrix.arch }}
      os: ${{ matrix.os.dist }}-${{ matrix.os.version }}
      compiler: vs${{ matrix.compiler.version }}
      generator: ${{ matrix.compiler.generator }}
      build: ${{ matrix.build }}
