name: Shion Windows Build
on:
  workflow_call:
    inputs:
      arch:
        type: string
        default: x64
      os:
        type: string
        default: windows-2022
      compiler:
        type: string
        default: vs2022
      generator:
        type: string
        default: Ninja
      build:
        type: string
        default: Debug
      cmake-flags:
        type: string
        default: ''
      pack:
        type: boolean
        default: false
    outputs:
      artifact:
        description: "Compiled server binaries"
        value: ${{ jobs.ci.outputs.artifact }}
  workflow_dispatch:
    inputs:
      arch:
        type: string
        default: x64
      os:
        type: string
        default: windows-2022
      compiler:
        type: string
        default: vs2022
      generator:
        type: string
        default: Ninja
      build:
        type: choice
        default: Debug
        options:
          - Debug
          - Release
          - RelWithDebInfo
      cmake-flags:
        type: string
        default: ''
      pack:
        type: boolean
        default: false

jobs:
  ci:
    name: ${{ inputs.compiler }}-${{ inputs.generator }} ${{ inputs.build }}
    outputs:
      artifact: ${{ steps.upload.outputs.artifact-id }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.10.2
        with:
          egress-policy: audit

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@1ff57057b5cfdc39105cd07a01d78e9b0ea0c14c # v1.3.1

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install chocolatey packages ${{ inputs.arch }}
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install CMake
        id: install-cmake
        uses: ./.github/actions/install-cmake
        with:
          version: 4.0.0-rc4

      - name: Generate CMake
        run: cmake . -B build -G "${{ inputs.generator }}" -DCMAKE_BUILD_TYPE=${{ inputs.build }} ${{ inputs.cmake-flags }}

      - name: Build Project
        run: cmake --build build --parallel 4
      
      - name: Package Project
        if: ${{ inputs.pack == true }}
        run: cmake --install build --prefix=build/pack

      - name: Upload Binaries
        id: upload
        if: ${{ inputs.pack == true }}
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: "Shion ${{ github.sha }} Windows ${{ inputs.arch }} ${{ inputs.compiler }} ${{ inputs.build }}"
          path: '${{github.workspace}}/build/pack/'
          retention-days: 30
